import type { z } from "zod/v4";
import type { EventEnvelope } from "@aestus/contracts";

/**
 * Metadata a producer supplies on publish. `payload_type` should be a canonical
 * name from `PAYLOAD_TYPES`; ids/timestamps are injectable for deterministic
 * fixtures (otherwise auto-generated by the envelope helper).
 */
export interface PublishOptions {
  source: string;
  payload_type: string;
  trace_id?: string;
  event_id?: string;
  emitted_at?: string;
}

/** A live subscription that can be torn down. */
export interface Subscription {
  unsubscribe(): Promise<void>;
}

/** Handler invoked with the validated payload and its full envelope. */
export type EventHandler<T> = (payload: T, envelope: EventEnvelope) => void | Promise<void>;

/** Request handler: receives the validated request, returns the response payload. */
export type RequestHandler<TReq, TRes> = (
  payload: TReq,
  envelope: EventEnvelope,
) => TRes | Promise<TRes>;

/** Per-subscription error hook for decode/validation/handler failures. */
export interface SubscribeOptions {
  /**
   * Called when an incoming message fails to decode/validate or the handler
   * throws. Receives the error, the raw bytes, and the subject it arrived on —
   * enough to dead-letter it (see `makeDeadLetterHandler`).
   */
  onError?: (error: unknown, raw: Uint8Array, subject: string) => void;
}

/**
 * Contract-validated event bus. The same interface is implemented by the
 * in-memory bus (fixture-first dev/tests) and the NATS-backed bus (runtime).
 */
export interface EventBus {
  /** Validate `payload` against `schema`, wrap in an envelope, and publish. */
  publish<T>(
    subject: string,
    payload: T,
    schema: z.ZodType<T>,
    options: PublishOptions,
  ): Promise<void>;

  /** Subscribe to `subject` (NATS wildcards allowed); deliver validated payloads. */
  subscribe<T>(
    subject: string,
    schema: z.ZodType<T>,
    handler: EventHandler<T>,
    options?: SubscribeOptions,
  ): Promise<Subscription>;

  /** Register a request/reply responder for `subject`. */
  respond<TReq, TRes>(
    subject: string,
    requestSchema: z.ZodType<TReq>,
    responseSchema: z.ZodType<TRes>,
    handler: RequestHandler<TReq, TRes>,
    options: PublishOptions,
  ): Promise<Subscription>;

  /** Send a request and await the validated response. */
  request<TReq, TRes>(
    subject: string,
    payload: TReq,
    requestSchema: z.ZodType<TReq>,
    responseSchema: z.ZodType<TRes>,
    options: PublishOptions & { timeoutMs?: number },
  ): Promise<{ payload: TRes; envelope: EventEnvelope }>;

  /** Flush and close the underlying connection. */
  close(): Promise<void>;
}

/** Thrown when an incoming message can be decoded but fails contract validation. */
export class ContractValidationError extends Error {
  constructor(
    message: string,
    readonly cause: unknown,
  ) {
    super(message);
    this.name = "ContractValidationError";
  }
}
